<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Fpe2001Remake.Scan\Fpe2001Remake.Scan.csproj" />
    <ProjectReference Include="..\..\src\Fpe2001Remake.Contracts\Fpe2001Remake.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Fpe2001Remake.Memory.Win32\Fpe2001Remake.Memory.Win32.csproj" />
  </ItemGroup>
</Project>
