<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Fpe2001Remake.Media</RootNamespace>
    <AssemblyName>Fpe2001Remake.Media</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fpe2001Remake.Contracts\Fpe2001Remake.Contracts.csproj" />
  </ItemGroup>

</Project>
